student:
   name: mokshi
   age: 222
   address: heaven

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     refresh:
       enabled: true     
spring:
   cloud:
      config:
         allow-override: true