student:
   name: mokshi12345
   age: 22212345
   address: heaven12345

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     refresh:
       enabled: true     
spring:
   cloud:
      config:
         allow-override: true