
spring:
   config:
     active:
       on-profile: dev

student:
   name: dev123
   age: 24
   address: heavenDev



spring:
   config:
     active:
       on-profile: test

student:
   name: test123
   age: 25
   address: heavenTest
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#     refresh:
#       enabled: true     
#spring:
#   cloud:
#      config:
#         allow-override: true