student:
   name: mokshi1
   age: 2221
   address: heaven1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     refresh:
       enabled: true     
spring:
   cloud:
      config:
         allow-override: true