student:
   name: l23gfsdgdfsd
   age: 2
   address: ne

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, env
  endpoint:
     refresh:
       enabled: true     
spring:
   cloud:
      config:
         allow-override: true