student:
   name: l23sd
   age: 2ssgdfg
   address: nessgdfg

management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, env
  endpoint:
     refresh:
       enabled: true     
spring:
   cloud:
      config:
         allow-override: true