#spring:
#   jpa:
#      database: mysql
#      show-sql: true
#      hibernate:
#         ddl-auto: update
#   datasource:
#      platform: mysql
#      url: jdbc:mysql://localhost:3306/myapp
#      username: root
#      password: root
#      driverClassName: com.mysql.cj.jdbc.Driver
#myapp:
#   storeid: c7c7
#   storename: rajarani
#   storelocation: mumbai
# spring.config.activate.on-profile=
---
spring:
   config:
      activate:
         on-profile: default
   jpa:
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto: update
   datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/myapp
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
myapp:
   storeid: c7c7
   storename: rajarani default
   storelocation: mumbai

...

---
spring:
   config:
      activate:
         on-profile: test
   jpa:
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto: update
   datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/myapp
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
myapp:
   storeid: gdfggf
   storename: fasni test
   storelocation: thane

...

---
spring:
   config:
      activate:
         on-profile: dev
   jpa:
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto: update
   datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/myapp
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
myapp:
   storeid: c54c7fsdf
   storename: god dev
   storelocation: pune

...

